spring:
  application:
    name: GameHub
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/gamehub
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true